language: node_js

node_js: node

services: 
  - docker

before_install:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
 - docker swarm init

install:
 - npm i

script: 
 - cd docker-node/
 - npm test
 - cd .. 
 - docker build -t jppanda/buildit-devops:node docker-node/
 - docker build -t jppanda/buildit-devops:lb docker-lb/

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

