#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push jppanda/buildit-devops:node
docker push jppanda/buildit-devops:lb
#docker-compose up -d
docker stack deploy --compose-file docker-compose.yml buildit-devops
